<template><main class="home-view">
  <div v-if="loading" class="home-loading" aria-live="polite">正在整理今天的信息…</div>
  <div v-else-if="error" class="home-error"><p>首页暂时无法加载。</p><button @click="load">重新加载</button></div>
  <template v-else-if="home">
    <p v-if="home.cache.status==='stale'" class="stale-banner">数据更新暂时延迟，当前显示最近一次结果。</p>
    <section class="today-card"><p class="eyebrow">{{ home.today.date }}</p><h1>今天</h1><p class="today-summary">{{ home.today.summary }}</p><div class="today-facts"><span>{{home.today.sources.healthy}} 个来源正常</span><span>{{home.today.sources.unhealthy}} 个来源异常</span><span>新发现 {{home.today.new_discovered}}</span><span>与我相关 {{home.today.relevant}}</span><span>已通知 {{home.today.notified}}</span></div></section>
    <button v-if="home.profile_status.status==='available'&&home.profile_status.needs_confirmation_count>0" class="profile-prompt" @click="profileOpen=!profileOpen">{{home.profile_status.message}}</button>
    <div v-if="profileOpen" class="profile-fields"><p v-for="field in home.profile_status.fields" :key="field.key">{{field.label}}：{{field.value||'待确认'}}</p></div>
    <div class="home-grid"><section class="recommendations"><h2>值得关注</h2><p v-if="!home.recommendations.items.length" class="empty">{{home.recommendations.empty_message}}</p><RecommendationCard v-for="item in home.recommendations.items" :key="`${item.title}-${item.published_at}`" :item="item" /></section>
    <section class="no-notification"><h2>最近为什么没通知我</h2><p>{{home.no_notification_summary.summary}}</p><p>真正新发布：{{home.no_notification_summary.true_new}}</p><ul><li v-for="category in home.no_notification_summary.categories" :key="category.code"><span>{{category.label}}</span><strong>{{category.count}}</strong></li></ul></section></div>
    <section class="ask"><h2>问小乐</h2><div class="quick-list"><button v-for="q in home.quick_questions" :key="q" data-test="quick-question" @click="ask(q)">{{q}}</button></div><div class="recent"><h3>最近会话</h3><button v-for="c in home.recent_conversations" :key="c.session_id" @click="router.push(`/chat/${c.session_id}`)">{{c.title}}</button></div></section>
    <section class="systems"><h2>系统状态</h2><div class="system-list"><article v-for="system in home.systems" :key="system.label" :class="system.status"><span class="dot"></span><div><strong>{{system.label}}</strong><p>{{system.message}}</p></div></article></div></section>
  </template>
</main></template>
<script setup>
import {onMounted,ref} from 'vue'; import {useRouter} from 'vue-router'; import api from '@/services/api'; import RecommendationCard from '@/home/components/RecommendationCard.vue'
const router=useRouter(),home=ref(null),loading=ref(true),error=ref(null),profileOpen=ref(false)
const load=async()=>{loading.value=true;error.value=null;try{home.value=await api.getHome()}catch(e){error.value=e}finally{loading.value=false}}
const ask=(question)=>router.push({path:'/chat',state:{xiaoleDraft:question,source:'home_quick_question'}})
onMounted(load)
</script>
<style scoped>
.home-view{width:min(100% - 40px,1120px);margin:0 auto;padding:32px 0 64px;color:var(--text-primary)}section{margin-bottom:24px}.today-card{padding:28px;border-radius:22px;background:linear-gradient(145deg,var(--bg-secondary),var(--bg-tertiary));border:1px solid var(--border-color)}h1{font-size:34px;margin:4px 0 12px}.eyebrow{color:var(--text-secondary);margin:0}.today-summary{font-size:18px;line-height:1.7}.today-facts,.quick-list,.system-list{display:flex;gap:10px;flex-wrap:wrap}.today-facts span{padding:7px 10px;background:var(--bg-primary);border-radius:10px}.profile-prompt,.quick-list button,.recent button,.home-error button{min-height:44px;border:1px solid var(--border-color);border-radius:12px;padding:8px 14px;background:var(--bg-secondary);color:var(--text-primary);cursor:pointer}.profile-prompt{width:100%;text-align:left;margin-bottom:12px}.profile-fields{padding:12px 18px;margin-bottom:24px;border-left:3px solid var(--primary-color)}.home-grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(260px,1fr);gap:24px}.recommendation-card{margin-bottom:12px}.no-notification{padding:20px;border:1px solid var(--border-color);border-radius:16px}.no-notification ul{padding:0;list-style:none}.no-notification li{display:flex;justify-content:space-between;padding:8px 0}.ask{padding:22px;border-radius:18px;background:var(--bg-secondary)}.recent{margin-top:18px}.recent button{margin-right:8px}.system-list article{display:flex;gap:10px;align-items:flex-start;flex:1;min-width:190px;padding:14px;border:1px solid var(--border-color);border-radius:14px}.system-list p{margin:4px 0 0;color:var(--text-secondary);font-size:13px}.dot{width:9px;height:9px;border-radius:50%;margin-top:5px;background:#ef4444}.healthy .dot{background:#22c55e}.degraded .dot{background:#f59e0b}.stale-banner{padding:10px 14px;border-radius:10px;background:#fff3cd;color:#765b00}.home-loading,.home-error{padding:50px 0;text-align:center}
@media(max-width:768px){.home-view{width:min(100% - 24px,1120px);padding:20px 0 max(32px,env(safe-area-inset-bottom))}.home-grid{display:flex;flex-direction:column}.ask{order:1}.today-card{padding:20px}.today-summary{font-size:16px}.quick-list button{width:100%;text-align:left}.system-list{flex-direction:column}.system-list article{width:100%;min-width:0;box-sizing:border-box}}
</style>
